### ISSUE TITLE
{feature request/suggestion} "comments" button

### ISSUE THREAD

**Issue by stapuft** [thorio/KGrabber#12]
first I just want to say I really love this amazing script I use it every day, and if I had a steady job I would gladly donate something to say thank you if there was a way i could do so. and that last update that gets the non capcha-ed links near instantly, without even reloading the page, *muah* perfection.

now for the feature request, because this is incompatible with the "complete capcha removal" script, to get to the comment section for a specific episode, you have to go through a capcha, it would be amazing if there was a "comment" button (....by the "grab" button maybe?) that when clicked, just takes you to the rapidvideo page so you can see the comments without doing a capcha..........BONUS POINTS if there was a way to block the player (to decrease load times, and/or prevent autoplay) and/or automatically open the comment section and focus on it

**Comment by thorio** [comment]
People actually use the comment section on kiss sites? 🙃 
I'd say this is out of the scope of this script though.

Anyway, here's some info: The reason it breaks the grabber is because it messes with the links on the page. It's not too hard to implement the same behavior without changed the href, so here you go:
```javascript
$(document.body).click((e) => {
	if (!e.target.href) {
		return;
	}
	if ($(e.target).is(".listing a")) {
		e.preventDefault();
		location.href = e.target.href + "&s=rapidvideo";
	}
})
```
Just drop this in a new userscript and you're good to go. For kimcartoon/kissasian replace `rapidvideo` with `rapid`.

**Comment by stapuft** [comment]
yeah man, the comment section is pretty much the only reason I still use kiss instead of 9anime or any other site that actually has dubbed anime....and okay thats essentially what I made for myself only much neeter, thank you.
