### ISSUE TITLE
compatibility issue with mal-sync

### ISSUE THREAD

**Issue by stapuft** [thorio/KGrabber#19]
**Describe the bug**
![image](https://user-images.githubusercontent.com/46431157/61987522-4c100280-afe5-11e9-9758-657520cdcc20.png)
this bar disappears when using the kissgrabber user script combined with the mal-sync extension, or userscript.
https://github.com/lolamtisch/MALSync
as far as I can tell there aren't any other compatibility issues, but this bar is essential for keeping track of the episodes you are on/have watched, and also easily allows you to update what episode you are on, especially when using the instant link grabber, which doesn't go to the video page itself.
**Information**
1. Browser: firefox 68.0.1
2. Userscript Manager:  tampermonkey

**Comment by lolamtisch** [comment]
It does not dissapears. It just gets injected into the settings page of the script.
I get the title and position for the UI throught `.bigChar`, but because the script injectes other ones here:
https://github.com/thorio/KGrabber/blob/master/KGrabber.user.js#L258
It ends up in the wrong place.

How do we want to fix it. Do you want to fix it on your side or should i fix it on my side? I just had a version release and i am not planning to release a new one too soon.

**Comment by thorio** [comment]
Then I'll just duplicate the class and set the color through js.
