### ISSUE TITLE
Could we see a 9anime version of this at some point in the future?

### ISSUE THREAD

**Issue by MXCIX** [thorio/KGrabber#2]
I noticed that you said "If you'd like to add a site, please open a new issue on GitHub." on the greasyfork page and i was wondering if that only pertained to the kiss website, and if not, what are the chances of a 9anime version?

**Comment by thorio** [comment]
I was talking about kiss sites, yes.
The kiss sites have a very similar structure, that's why it's possible to write a single script for all of them.
Adding other sites would require increasing complexity of the script, to the point that it would probably be easier to duplicate it / write a new script.
So most likely not, sorry.
