### ISSUE TITLE
Option for IDM batch file is greyed out

### ISSUE THREAD

**Issue by hemlok89** [thorio/KGrabber#29]
Hello, after the recent HydraX nuisance the script only shows list, JSON & CSV as exporting option. Here is a [screenshot ](https://i.imgur.com/9fM2hb1.png)

**Information**
1. Browser: Chrome 78
2. Userscript Manager: Tampermonkey
3. Show, Episode: [Non Non Biyori](https://kissanime.ru/Anime/Non-Non-Biyori)
4. Server: HydraX

**Comment by thorio** [comment]
This is **completely intentional**.
Afaik, there's no way to get direct links for HydraX because they use HLS streams.
The links you have there are embed links, and downloading those would net you useless html.

Since rapid appears to be dead, I have been using Nova. You'll have to deal with the captchas, but after that you can use IDM as normal.
