### ISSUE TITLE
tutorial for....that one program

### ISSUE THREAD

**Issue by stapuft** [thorio/KGrabber#4]
I remember you had said on reddit but can't find said thread now, that you could use a command line program to take links and turn them into direct video links, could you possibly do a tutorial on exactly how to do that, what the program even is, and what list format to chose when doing do?

thanks so much for the great userscript.

**Comment by thorio** [comment]
Basically download [youtube-dl.exe](https://github.com/ytdl-org/youtube-dl/releases) and drop it into `C:/Windows/`. Then you can use `youtube-dl -g [link1] [link2]` etc. in cmd to get direct links. It also has a ton more features documented [here](https://github.com/ytdl-org/youtube-dl/blob/master/README.md).

**Comment by stapuft** [comment]
what do you mean by "use"? open up the command prompt and type that string of chars? 
so I don't pick any list type? I just copy the plaintext link list?
do I have to use brackets [] to seperate the links like you did there or just paste the links in?

**Comment by thorio** [comment]
That's why it's a command line tool, it offers lots of options for those who know how to use it.
Here's an example:
![image](https://user-images.githubusercontent.com/39875034/59495836-7459fc80-8e90-11e9-99c6-d2f61b102963.png)
To get rid of the warnings so you can copy the links use `--no-warnings` like so:
![image](https://user-images.githubusercontent.com/39875034/59495917-a9fee580-8e90-11e9-979b-d282102fb5b2.png)
You can also omit the `-g` parameter to download.
